package rainbow

func (t Text) Aqua() Text              { return t.Color("aqua") }
func (t Text) Aquamarine() Text        { return t.Color("aquamarine") }
func (t Text) Mediumaquamarine() Text  { return t.Color("mediumaquamarine") }
func (t Text) Azure() Text             { return t.Color("azure") }
func (t Text) Beige() Text             { return t.Color("beige") }
func (t Text) Bisque() Text            { return t.Color("bisque") }
func (t Text) Blanchedalmond() Text    { return t.Color("blanchedalmond") }
func (t Text) Darkblue() Text          { return t.Color("darkblue") }
func (t Text) Lightblue() Text         { return t.Color("lightblue") }
func (t Text) Mediumblue() Text        { return t.Color("mediumblue") }
func (t Text) Aliceblue() Text         { return t.Color("aliceblue") }
func (t Text) Cadetblue() Text         { return t.Color("cadetblue") }
func (t Text) Dodgerblue() Text        { return t.Color("dodgerblue") }
func (t Text) Midnightblue() Text      { return t.Color("midnightblue") }
func (t Text) Navyblue() Text          { return t.Color("navyblue") }
func (t Text) Powderblue() Text        { return t.Color("powderblue") }
func (t Text) Royalblue() Text         { return t.Color("royalblue") }
func (t Text) Skyblue() Text           { return t.Color("skyblue") }
func (t Text) Deepskyblue() Text       { return t.Color("deepskyblue") }
func (t Text) Lightskyblue() Text      { return t.Color("lightskyblue") }
func (t Text) Slateblue() Text         { return t.Color("slateblue") }
func (t Text) Darkslateblue() Text     { return t.Color("darkslateblue") }
func (t Text) Mediumslateblue() Text   { return t.Color("mediumslateblue") }
func (t Text) Steelblue() Text         { return t.Color("steelblue") }
func (t Text) Lightsteelblue() Text    { return t.Color("lightsteelblue") }
func (t Text) Brown() Text             { return t.Color("brown") }
func (t Text) Rosybrown() Text         { return t.Color("rosybrown") }
func (t Text) Saddlebrown() Text       { return t.Color("saddlebrown") }
func (t Text) Sandybrown() Text        { return t.Color("sandybrown") }
func (t Text) Burlywood() Text         { return t.Color("burlywood") }
func (t Text) Chartreuse() Text        { return t.Color("chartreuse") }
func (t Text) Chocolate() Text         { return t.Color("chocolate") }
func (t Text) Coral() Text             { return t.Color("coral") }
func (t Text) Lightcoral() Text        { return t.Color("lightcoral") }
func (t Text) Cornflower() Text        { return t.Color("cornflower") }
func (t Text) Cornsilk() Text          { return t.Color("cornsilk") }
func (t Text) Crimson() Text           { return t.Color("crimson") }
func (t Text) Darkcyan() Text          { return t.Color("darkcyan") }
func (t Text) Lightcyan() Text         { return t.Color("lightcyan") }
func (t Text) Firebrick() Text         { return t.Color("firebrick") }
func (t Text) Fuchsia() Text           { return t.Color("fuchsia") }
func (t Text) Gainsboro() Text         { return t.Color("gainsboro") }
func (t Text) Gold() Text              { return t.Color("gold") }
func (t Text) Goldenrod() Text         { return t.Color("goldenrod") }
func (t Text) Darkgoldenrod() Text     { return t.Color("darkgoldenrod") }
func (t Text) Lightgoldenrod() Text    { return t.Color("lightgoldenrod") }
func (t Text) Palegoldenrod() Text     { return t.Color("palegoldenrod") }
func (t Text) Gray() Text              { return t.Color("gray") }
func (t Text) Darkgray() Text          { return t.Color("darkgray") }
func (t Text) Dimgray() Text           { return t.Color("dimgray") }
func (t Text) Lightgray() Text         { return t.Color("lightgray") }
func (t Text) Slategray() Text         { return t.Color("slategray") }
func (t Text) Lightslategray() Text    { return t.Color("lightslategray") }
func (t Text) Webgray() Text           { return t.Color("webgray") }
func (t Text) Darkgreen() Text         { return t.Color("darkgreen") }
func (t Text) Lightgreen() Text        { return t.Color("lightgreen") }
func (t Text) Palegreen() Text         { return t.Color("palegreen") }
func (t Text) Darkolivegreen() Text    { return t.Color("darkolivegreen") }
func (t Text) Yellowgreen() Text       { return t.Color("yellowgreen") }
func (t Text) Forestgreen() Text       { return t.Color("forestgreen") }
func (t Text) Lawngreen() Text         { return t.Color("lawngreen") }
func (t Text) Limegreen() Text         { return t.Color("limegreen") }
func (t Text) Seagreen() Text          { return t.Color("seagreen") }
func (t Text) Darkseagreen() Text      { return t.Color("darkseagreen") }
func (t Text) Lightseagreen() Text     { return t.Color("lightseagreen") }
func (t Text) Mediumseagreen() Text    { return t.Color("mediumseagreen") }
func (t Text) Springgreen() Text       { return t.Color("springgreen") }
func (t Text) Mediumspringgreen() Text { return t.Color("mediumspringgreen") }
func (t Text) Webgreen() Text          { return t.Color("webgreen") }
func (t Text) Honeydew() Text          { return t.Color("honeydew") }
func (t Text) Indianred() Text         { return t.Color("indianred") }
func (t Text) Indigo() Text            { return t.Color("indigo") }
func (t Text) Ivory() Text             { return t.Color("ivory") }
func (t Text) Khaki() Text             { return t.Color("khaki") }
func (t Text) Darkkhaki() Text         { return t.Color("darkkhaki") }
func (t Text) Lavender() Text          { return t.Color("lavender") }
func (t Text) Lavenderblush() Text     { return t.Color("lavenderblush") }
func (t Text) Lemonchiffon() Text      { return t.Color("lemonchiffon") }
func (t Text) Lime() Text              { return t.Color("lime") }
func (t Text) Linen() Text             { return t.Color("linen") }
func (t Text) Darkmagenta() Text       { return t.Color("darkmagenta") }
func (t Text) Maroon() Text            { return t.Color("maroon") }
func (t Text) Webmaroon() Text         { return t.Color("webmaroon") }
func (t Text) Mintcream() Text         { return t.Color("mintcream") }
func (t Text) Mistyrose() Text         { return t.Color("mistyrose") }
func (t Text) Moccasin() Text          { return t.Color("moccasin") }
func (t Text) Oldlace() Text           { return t.Color("oldlace") }
func (t Text) Olive() Text             { return t.Color("olive") }
func (t Text) Olivedrab() Text         { return t.Color("olivedrab") }
func (t Text) Orange() Text            { return t.Color("orange") }
func (t Text) Darkorange() Text        { return t.Color("darkorange") }
func (t Text) Orchid() Text            { return t.Color("orchid") }
func (t Text) Darkorchid() Text        { return t.Color("darkorchid") }
func (t Text) Mediumorchid() Text      { return t.Color("mediumorchid") }
func (t Text) Papayawhip() Text        { return t.Color("papayawhip") }
func (t Text) Peachpuff() Text         { return t.Color("peachpuff") }
func (t Text) Peru() Text              { return t.Color("peru") }
func (t Text) Pink() Text              { return t.Color("pink") }
func (t Text) Deeppink() Text          { return t.Color("deeppink") }
func (t Text) Lightpink() Text         { return t.Color("lightpink") }
func (t Text) Hotpink() Text           { return t.Color("hotpink") }
func (t Text) Plum() Text              { return t.Color("plum") }
func (t Text) Purple() Text            { return t.Color("purple") }
func (t Text) Mediumpurple() Text      { return t.Color("mediumpurple") }
func (t Text) Rebeccapurple() Text     { return t.Color("rebeccapurple") }
func (t Text) Webpurple() Text         { return t.Color("webpurple") }
func (t Text) Darkred() Text           { return t.Color("darkred") }
func (t Text) Orangered() Text         { return t.Color("orangered") }
func (t Text) Mediumvioletred() Text   { return t.Color("mediumvioletred") }
func (t Text) Palevioletred() Text     { return t.Color("palevioletred") }
func (t Text) Salmon() Text            { return t.Color("salmon") }
func (t Text) Darksalmon() Text        { return t.Color("darksalmon") }
func (t Text) Lightsalmon() Text       { return t.Color("lightsalmon") }
func (t Text) Seashell() Text          { return t.Color("seashell") }
func (t Text) Sienna() Text            { return t.Color("sienna") }
func (t Text) Silver() Text            { return t.Color("silver") }
func (t Text) Darkslategray() Text     { return t.Color("darkslategray") }
func (t Text) Snow() Text              { return t.Color("snow") }
func (t Text) Tan() Text               { return t.Color("tan") }
func (t Text) Teal() Text              { return t.Color("teal") }
func (t Text) Thistle() Text           { return t.Color("thistle") }
func (t Text) Tomato() Text            { return t.Color("tomato") }
func (t Text) Turquoise() Text         { return t.Color("turquoise") }
func (t Text) Darkturquoise() Text     { return t.Color("darkturquoise") }
func (t Text) Mediumturquoise() Text   { return t.Color("mediumturquoise") }
func (t Text) Paleturquoise() Text     { return t.Color("paleturquoise") }
func (t Text) Violet() Text            { return t.Color("violet") }
func (t Text) Darkviolet() Text        { return t.Color("darkviolet") }
func (t Text) Blueviolet() Text        { return t.Color("blueviolet") }
func (t Text) Wheat() Text             { return t.Color("wheat") }
func (t Text) Antiquewhite() Text      { return t.Color("antiquewhite") }
func (t Text) Floralwhite() Text       { return t.Color("floralwhite") }
func (t Text) Ghostwhite() Text        { return t.Color("ghostwhite") }
func (t Text) Navajowhite() Text       { return t.Color("navajowhite") }
func (t Text) Whitesmoke() Text        { return t.Color("whitesmoke") }
func (t Text) Lightyellow() Text       { return t.Color("lightyellow") }
func (t Text) Greenyellow() Text       { return t.Color("greenyellow") }
